/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.JOptionPane;

/**

 */
public class panelprincipal extends javax.swing.JFrame {

    /**
     * Creates new form panelprincipal
     */
    public panelprincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Ventas");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            
    int pantalon=100,camisa=100,medias=100,tenis=100,gorras=100,productos,total,total1,totalp;
    int cpantalon=20000,ccamisa=10000,cmedias=3000,ctenis=60000,cgorras=15000;
    int Vpantalon=30000,Vcamisa=25000,Vmedias=8000,Vtenis=70000,Vgorras=20000;
    int npantalon,ncamisa,nmedias,ntenis,ngorras,nproductos,ntotal,efectivo;
    int totalc,efecti,venta;
    String  TOTAL,V;
    int vEnero,vFebrero,vMarzo,vAbril,vMayo,vJunio,vJulio,vAgosto,vSeptiembre,vOctubre,vNoviembre,vDiciembre;
    String tEnero,tFebrero,tMarzo,tAbril,tMayo,tJunio,tJulio,tAgosto,tSeptiembre,tOctubre,tNoviembre,tDiciembre;
    int Spantalon,Scamisa,Smedias,Stenis,Sgorras;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reporte = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        L13 = new javax.swing.JLabel();
        T6 = new javax.swing.JTextField();
        T7 = new javax.swing.JTextField();
        T8 = new javax.swing.JTextField();
        T9 = new javax.swing.JTextField();
        T10 = new javax.swing.JTextField();
        Vender = new javax.swing.JButton();
        L14 = new javax.swing.JLabel();
        T11 = new javax.swing.JTextField();
        L15 = new javax.swing.JLabel();
        T12 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        T20 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        C2 = new javax.swing.JComboBox();
        ver = new javax.swing.JButton();
        C1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.red);
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        reporte.setText("Reporte Inversiones");
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });

        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 15, 0));
        l1.setText("BIENVENIDO a RonnyShop ");

        L8.setFont(new java.awt.Font("Old English Text MT", 3, 24)); // NOI18N
        L8.setText("CATALOGO DE PRODUCTOS ");

        L9.setText("Pantalon");

        L10.setText("local");

        L11.setText("Medias");

        L12.setText("nacional");

        L13.setText("gorras");

        T7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T7ActionPerformed(evt);
            }
        });

        Vender.setText("comprar ");
        Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderActionPerformed(evt);
            }
        });

        L14.setText("Cambio");

        T11.setEditable(false);
        T11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T11ActionPerformed(evt);
            }
        });

        L15.setText("Efectivo");

        jLabel1.setText("ingrese el mes de la compra:");

        jLabel2.setText("Total");

        T20.setEditable(false);

        jLabel3.setText("Seleccione el mes que dese ver:");

        jLabel4.setText("REPORTE DE VENTAS");

        C2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        ver.setText("Ver");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });

        C1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel9.setText("$70.000");

        jLabel11.setText("$20.000");

        jLabel12.setText("$20.000");

        jLabel13.setText("$30.000");

        jLabel14.setText("$8.000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L10)
                    .addComponent(T7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L8))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L9)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(l1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(L12)
                                .addComponent(T9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(L13)
                                .addComponent(T10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(reporte)
                        .addGap(10, 10, 10)
                        .addComponent(jButton7)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(L15)
                        .addGap(10, 10, 10)
                        .addComponent(T12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(L14)
                        .addGap(18, 18, 18)
                        .addComponent(T11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(T20, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L11)
                            .addComponent(jLabel14))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(T8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Vender, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L8)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(T7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L9)
                        .addGap(18, 18, 18)
                        .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(L12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(T9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(L13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(T10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(110, 110, 110)
                        .addComponent(L11)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Vender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(T12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L15)
                                    .addComponent(L14)
                                    .addComponent(jLabel2))))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reporte)
                            .addComponent(jButton7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ver))
                        .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderActionPerformed
        efecti = Integer.parseInt(T12.getText());
        npantalon = Integer.parseInt(T6.getText());
        ncamisa   = Integer.parseInt(T7.getText());
        nmedias   = Integer.parseInt(T8.getText());
        ntenis  = Integer.parseInt(T9.getText());
        ngorras = Integer.parseInt(T10.getText()); 
//        efectivo = Integer.parseInt(T12.getText());
        
        
         Spantalon= Vpantalon*npantalon;
         Scamisa  = Vcamisa*ncamisa;
         Smedias  = Vmedias*nmedias;
         Stenis = Vtenis*ntenis;
         Sgorras= Vgorras*ngorras;
        
         pantalon = pantalon-npantalon;
         camisa   = camisa-ncamisa;
         medias   = medias-nmedias;
         tenis  = tenis-ntenis;
         gorras = gorras-ngorras;
        
         if(pantalon <8)
             JOptionPane.showMessageDialog(null,"Quedan "+pantalon+" Pantalones");
         
         if(camisa < 8)
             JOptionPane.showMessageDialog(null,"Quedan "+ camisa + " camisas");
         
         if(medias < 8)
             JOptionPane.showMessageDialog(null,"Quedan " + medias +" medias");
             
         if(tenis < 8)
             JOptionPane.showMessageDialog(null,"Quedan "+ tenis +" tenis");    
                 
         if(gorras < 8)
              JOptionPane.showMessageDialog(null,"Quedan "+ gorras + " gorras");       


        total1 = Spantalon+Scamisa+Smedias+Stenis+Sgorras;
        totalc=totalc+total1;
        TOTAL=Integer.toString(totalc);
        venta=efecti-total1;
        String T=Integer.toString(total1);
        T20.setText(T);
        T11.setText(venta+"");
          if(C1.getSelectedItem().equals("Enero")){
            vEnero=vEnero+total1;
        }else{if(C1.getSelectedItem().equals("Febrero")){
            vFebrero=vFebrero+total1;
        }else{if(C1.getSelectedItem().equals("Marzo")){
            vMarzo=vMarzo+total1;
        }else{if(C1.getSelectedItem().equals("Abril")){
            vAbril=vAbril+total1;
        }else{if(C1.getSelectedItem().equals("Mayo")){
            vMayo=vMayo+total1;
        }else{if(C1.getSelectedItem().equals("Junio")){
            vJunio=vJunio+total1;
        }else{if(C1.getSelectedItem().equals("Julio")){
            vJulio=vJulio+total1;
        }else{if(C1.getSelectedItem().equals("Agosto")){
            vAgosto=vAgosto+total1;
        }else{if(C1.getSelectedItem().equals("Septiembre")){
            vEnero=vEnero+total1;
        }else{if(C1.getSelectedItem().equals("Octubre")){
            vSeptiembre=vSeptiembre+total1;
        }else{if(C1.getSelectedItem().equals("Noviembre")){
            vNoviembre=vNoviembre+total1;
        }else{if(C1.getSelectedItem().equals("Diciembre")){
            vDiciembre=vDiciembre+total1;
        }else{
            JOptionPane.showMessageDialog(null, "Seleecione una opcion");
        }}}}}}}}}}}}
          vEnero++;
          vFebrero++;
          vMarzo++;
          vAbril++;
          vMayo++;
          vJunio++;
          vJulio++;
          vAgosto++;
          vSeptiembre++;
          vOctubre++;
          vNoviembre++;
          vDiciembre++;
               
        
//        JOptionPane.showMessageDialog(null,"Valor a Pagar: "+total1);
//        efectivo= JOptionPane.showInputDialog("Efectivo:");     
// TODO add your handling code here:
    }//GEN-LAST:event_VenderActionPerformed

    private void T11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
            JOptionPane.showMessageDialog(null, ("Pantalones:  "+pantalon
                                             +" \nCamisas: "+camisa
                                             +" \nMedias:  "+medias
                                             +" \ntenis: "+tenis
                                             +" \ngorras: "+gorras
                                             +" \nProducto total: " +TOTAL
                                              ));
        // TODO add your handling code here:
    }//GEN-LAST:event_reporteActionPerformed

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
              
          if(C2.getSelectedItem().equals("Enero")){
            JOptionPane.showMessageDialog(null,"reporte : " + vEnero);
        }else{if(C2.getSelectedItem().equals("Febrero")){
            JOptionPane.showMessageDialog(null,"reporte : " + vFebrero);
        }else{if(C2.getSelectedItem().equals("Marzo")){
            JOptionPane.showMessageDialog(null,"reporte : " + vMarzo);
        }else{if(C2.getSelectedItem().equals("Abril")){
            JOptionPane.showMessageDialog(null,"reporte : " + vAbril);
        }else{if(C2.getSelectedItem().equals("Mayo")){
            JOptionPane.showMessageDialog(null,"reporte : " + vMayo);
        }else{if(C2.getSelectedItem().equals("Junio")){
            JOptionPane.showMessageDialog(null,"reporte : " + vJunio);
        }else{if(C2.getSelectedItem().equals("Julio")){
           JOptionPane.showMessageDialog(null,"reporte : " + vJulio);
        }else{if(C2.getSelectedItem().equals("Agosto")){
            JOptionPane.showMessageDialog(null,"reporte : " + vAgosto);
        }else{if(C2.getSelectedItem().equals("Septiembre")){
           JOptionPane.showMessageDialog(null,"reporte : " + vSeptiembre);
        }else{if(C2.getSelectedItem().equals("Octubre")){
            JOptionPane.showMessageDialog(null,"reporte : " + vOctubre);
        }else{if(C2.getSelectedItem().equals("Noviembre")){
            JOptionPane.showMessageDialog(null,"reporte : " + vNoviembre);
        }else{if(C2.getSelectedItem().equals("Diciembre")){
           JOptionPane.showMessageDialog(null,"reporte : " + vDiciembre);
        }else{
            JOptionPane.showMessageDialog(null, "Seleecione una opcion");
        }}}}}}}}}}}}  // TODO add your handling code here:
    }//GEN-LAST:event_verActionPerformed

    private void T7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox C1;
    private javax.swing.JComboBox C2;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L12;
    private javax.swing.JLabel L13;
    private javax.swing.JLabel L14;
    private javax.swing.JLabel L15;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JTextField T10;
    private javax.swing.JTextField T11;
    private javax.swing.JTextField T12;
    private javax.swing.JTextField T20;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JTextField T9;
    private javax.swing.JButton Vender;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel l1;
    private javax.swing.JButton reporte;
    private javax.swing.JButton ver;
    // End of variables declaration//GEN-END:variables

    private Object getclass() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
